### PR TITLE
Update command to install nacl in install-hub.sh

### PR DESCRIPTION
**Pull request by A-Harby**
Update command to install nacl in install-hub.sh

### CODE REVIEW

**Review by coesensbert — APPROVED** [review]
Not sure we can leave out the pip3 install's but I'll leave that up to you, thanks.

**Comment by mik-tf** [comment]
@coesensbert It is OK to remove the pip steps as the steps above added the packages at the user level.

**Comment by coesensbert** [comment]
> @coesensbert It is OK to remove the pip steps as the steps above added the packages at the user level.

ok, I should clarify better. What I mean was that while building this thing, I remember doing the opposite. So not installingvia apt, but via pip3 install ... to fix issues with nacl. So I fear it might be ubuntu version dependent since I tested on 24.04

**Comment by mik-tf** [comment]
OK I see. Do you think we should have more test then? Try apt vs pip3?

@coesensbert The issue was really with this: --break-system-packages, not pip itself.

So we could do

```
apt update && apt install python3 python3-requests python3-pip -y
pip3 install pynacl
pip3 install redis
```

LMK if we should test this. Sorry if I merged too quickly!

**Comment by mik-tf** [comment]
Testing on docker ubuntu 24:

image

**Comment by coesensbert** [comment]
Don't know what is best, if it's ok for Harby it's ok for me with the merged PR

**Pull request merged**
